server:
  port: 6000
  context-path: /geo-converter
#yandex:
#  ribbon:
#    listOfServers: https://geocode-maps.yandex.ru/1.x/
#    ConnectTimeout: 20000
#    ReadTimeout: 20000
#    IsSecure: true
#hystrix.command.default.execution:
#  timeout.enabled: true
#  isolation.thread.timeoutInMilliseconds: 50000

yandex:
  url: https://geocode-maps.yandex.ru/1.x/
  format: json